/**
 * PharmaTrace Supply Chain Information Network API
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: api@pharmatrace.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Container { 
    /**
     * Unique identifier representing a specific container.
     */
    containerId?: string;
    /**
     * EPC code
     */
    epcCode?: string;
    /**
     * Serialization label.
     */
    label?: string;
    /**
     * barcode on container. Normally equal to container id.
     */
    barcode?: string;
    /**
     * RFID of RF tracking label on conatiner.
     */
    rfId?: string;
    /**
     * quantity of product in container.
     */
    quantity?: number;
    /**
     * Unit for quantity measurement.
     */
    unit?: string;
    /**
     * Location id of last tracked locaction.
     */
    currentLocationId?: string;
    /**
     * stakeholder id of the last tracked owner of the container.
     */
    ownerStakeholderId?: string;
    /**
     * id of the parent container or null.
     */
    parentContainerId?: string;
}
