/**
 * PharmaTrace Supply Chain Information Network API
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: api@pharmatrace.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LegalTxTerms { 
    /**
     * GMT, Unix Epoch
     */
    timestampValidFrom?: number;
    /**
     * GMT, Unix Epoch
     */
    timestampValidUntil?: number;
    /**
     * tolerance window for transactions that begin but do not finish under the governance of these terms (in ms)
     */
    validityTolerance?: number;
    /**
     * unique id hash of the transaction terms and conditions
     */
    termsId?: string;
    /**
     * optional version mark of the terms
     */
    termsVersion?: string;
    /**
     * optional link to the previous version of these terms
     */
    termsIdPreviousVersion?: string;
    /**
     * text of the terms and conditions
     */
    termsText?: string;
    /**
     * ISO language code, e.g. en_us
     */
    language?: string;
    /**
     * legislation enforcing these terms
     */
    legislation?: string;
}
