export * from './activitys.service';
import { ActivitysService } from './activitys.service';
export * from './container.service';
import { ContainerService } from './container.service';
export * from './containers.service';
import { ContainersService } from './containers.service';
export * from './informationQueryResponses.service';
import { InformationQueryResponsesService } from './informationQueryResponses.service';
export * from './informationQuerys.service';
import { InformationQuerysService } from './informationQuerys.service';
export * from './legalTxTermss.service';
import { LegalTxTermssService } from './legalTxTermss.service';
export * from './locations.service';
import { LocationsService } from './locations.service';
export * from './pharmaceuticals.service';
import { PharmaceuticalsService } from './pharmaceuticals.service';
export * from './profiles.service';
import { ProfilesService } from './profiles.service';
export * from './repackages.service';
import { RepackagesService } from './repackages.service';
export * from './stakeholders.service';
import { StakeholdersService } from './stakeholders.service';
export * from './systemInformations.service';
import { SystemInformationsService } from './systemInformations.service';
export * from './trades.service';
import { TradesService } from './trades.service';
export * from './transports.service';
import { TransportsService } from './transports.service';
export * from './user.service';
import { UserService } from './user.service';
export * from './wallets.service';
import { WalletsService } from './wallets.service';
export const APIS = [ActivitysService, ContainerService, ContainersService, InformationQueryResponsesService, InformationQuerysService, LegalTxTermssService, LocationsService, PharmaceuticalsService, ProfilesService, RepackagesService, StakeholdersService, SystemInformationsService, TradesService, TransportsService, UserService, WalletsService];
